### ISSUE TITLE
Сломанная навигация

### ISSUE THREAD

**Issue by Dodje** [miklern/vueRouter#10]
https://github.com/miklern/vueRouter/blob/98eced61b774eeda0d37e7c5b75aaa0408813202/src/pages/Home.vue#L5

Вообще говоря, если ты делаешь полностью навигацию по ссылкам, то тебе надо сделать структуру, которая будет
в компоненте навигации формировать ссылки и хранить их для использования
Тогда при переходе на страницу `info/:id`, надо через `route` получать это id, и по нему делать запрос данных

Либо можно не делать ссылкой и компонент родиель должен хранить выбранный id и передавать дальше в Info component через props, а сейчас оно все просто кучей

**Comment by miklern** [comment]
Вроде сделал всё как надо
