### ISSUE TITLE
Пути в ссылке

### ISSUE THREAD

**Issue by Dodje** [miklern/vueRouter#2]
https://github.com/miklern/vueRouter/blob/98eced61b774eeda0d37e7c5b75aaa0408813202/src/router/router.js#L16

не считая динамических переменных :id/:albumId и тп, не совсем понятно, почему пути прописаны с большой буквы, так задумано?
то, что ты пишешь в path отображается в адресной строке

**Comment by miklern** [comment]
Нет, так не задумано, не знал, что так нельзя, больше так прописывать не буду.

**Comment by Dodje** [comment]
Здесь дело не в том, что нельзя - технически можно, просто было интересно, до конца ли понятно, что то, что описано в роутере, будет отрабатывать в поисковой строке (ещё регистр иногда важен)

**Comment by miklern** [comment]
Да, не до конца было понятно, прочитал несколько статей, теперь понял почему регистр важен.
