### ISSUE TITLE
Некорректные названия сущностей

### ISSUE THREAD

**Issue by Dodje** [miklern/vueRouter#5]
https://github.com/miklern/vueRouter/blob/98eced61b774eeda0d37e7c5b75aaa0408813202/src/pages/Home.vue#L7

Ты назвал свою структуру списком имен, при этом у name появилось свойство id, которое ты присваиващем к activeName

По факту, это сущность аля userInList, у которой есть id. А выбираешь ты activeUserId, а не name

**Comment by miklern** [comment]
Сущности переименовал.
