### ISSUE TITLE
Напоминаю, задачу и структуру

### ISSUE THREAD

**Issue by Dodje** [miklern/vueRouter#6]
Должно быть

страница Home, где есть 2 компонента: меню навигации и странциа профиля с альбомами.
если не был выбран профиль - можно выводить: "Ни один из профилей (юзер) не выбран"
страница Photos (тут немного переиначим): список юзеров слева не показываем, выводим фотки, как есть, но в хлебных крошках надо сохранить ссылку на профиль текущего юзера

**Comment by miklern** [comment]
Сделал
